### ISSUE TITLE
Conrad crashes if ModMenu is not installed but does not declare ModMenu as a dependency

### ISSUE THREAD

**Issue by CmdrNorthpaw** [Hephaestus-Dev/Conrad#12]
Conrad's compatibility with ModMenu is pretty great, but there is a small issue with it, in that it requires ModMenu to not crash but doesn't declare it as a dependency in `fabric.mod.json`. This can be easily worked around by a developer but is confusing for the end user, who may not be able to easily read Java crashes. There are a couple of possible solutions to this: You can rewrite the ModMenu integration so that Conrad only attempts to access ModMenu classes if ModMenu is installed, or you can declare ModMenu as a dependency in `fabric.mod.json`. I've opened a pull request to the latter effect, but if you think the former approach would be better you can just reject it.

**Comment by Haven-King** [comment]
As mentioned on the PR, I will change the GUI slightly so that Mod Menu is not a strict requirement.
